// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_document from "./routes/_document.tsx";
import * as $api_contact from "./routes/api/contact.ts";
import * as $index from "./routes/index.tsx";
import * as $ContactForm from "./islands/ContactForm.tsx";
import * as $LogoCarousel from "./islands/LogoCarousel.tsx";
import * as $MobileMenu from "./islands/MobileMenu.tsx";
import * as $SmoothScroll from "./islands/SmoothScroll.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_document.tsx": $_document,
    "./routes/api/contact.ts": $api_contact,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ContactForm.tsx": $ContactForm,
    "./islands/LogoCarousel.tsx": $LogoCarousel,
    "./islands/MobileMenu.tsx": $MobileMenu,
    "./islands/SmoothScroll.tsx": $SmoothScroll,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
